config/routes.rb
BrewApp::Application.routes.draw do
  devise_for :users
  root "brews#index"

  resources :brews
end

app/models/brew.rb
class Brew < ActiveRecord::Base
	belongs_to :user
	has_many :fermentables
	has_many :extras
	has_many :hops
	has_many :yeasts
	has_many :comments
	accepts_nested_attributes_for :hops, allow_destroy: true
	accepts_nested_attributes_for :fermentables, allow_destroy: true
	accepts_nested_attributes_for :extras, allow_destroy: true
	accepts_nested_attributes_for :yeasts, allow_destroy: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :brew
end

app/models/extra.rb
class Extra < ActiveRecord::Base
  belongs_to :brew
end

app/models/fermentable.rb
class Fermentable < ActiveRecord::Base
  belongs_to :brew
end

app/models/hop.rb
class Hop < ActiveRecord::Base
  belongs_to :brew
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :email, uniqueness: true

   has_many :brews
   has_many :comments
end

app/models/yeast.rb
class Yeast < ActiveRecord::Base
  belongs_to :brew
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brews_controller.rb
class BrewsController < ApplicationController
  def index
  	@brews = Brew.all
  end

  def new
  	@brew = Brew.new
  	@brew.hops.build
    @brew.fermentables.build
    @brew.yeasts.build
    @brew.extras.build
  end

  def show
  	@brew = Brew.find params[:id]
  end

  def edit
    @brew = Brew.find params[:id]
  end

  def create
  	@brew = Brew.new(brew_params)
    @brew.user = User.find(current_user.id)
   	if @brew.save
   		redirect_to @brew
   	else
   		'new'
   	end
  end

 def update
  @brew = Brew.find params[:id]
  @brew.update brew_params
  redirect_to @brew
 end


private 
  def brew_params
  	params.require('brew').permit(:name, :story, :walkthrough, hops_attributes: [:name, :id, :brew_id], 
      extras_attributes: [:name, :id, :brew_id], fermentables_attributes: [:name, :id, :brew_id], 
      yeasts_attributes: [:name, :id, :brew_id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/brews_helper.rb
module BrewsHelper
end

app/views/brews/_extras.html.erb
	<p>
		<%=  f.label :name, "Extras" %>
		<%=  f.text_field :name %>
	

	</p>

app/views/brews/_fermentables.html.erb
<p>
		<%=  f.label :name, "Fermentables" %>
		<%=  f.text_field :name %>
		
</p>

app/views/brews/_form.html.erb
<%= form_for @brew do |f| %>
	<fieldset>
	<p><%= f.label :name, "Beer Name" %> <br />
		<%= f.text_field :name %><br />
		<%= f.label :story, "Brew Story" %><br />
		<%= f.text_area :story %><br />
		<%= f.label :walkthrough, "Recipe Walkthrough" %><br />
		<%= f.text_area :walkthrough %><br />
	</p>
	</fieldset>

			<%= f.fields_for :fermentables do |fermentables| %>
				<%= render 'fermentables', f: fermentables %>
			<% end %>
			
			
			<%= f.fields_for :hops do |hops| %>
				<%= render 'hops', f: hops %>
			<% end %>
		


			<%= f.fields_for :yeasts do |yeasts| %>
				<%= render 'yeasts', f: yeasts %>
			<% end %>
		

			<%= f.fields_for :extras do |extras| %>
				<%= render 'extras', f: extras %>
			<% end %>
	

	<p>
		<%= f.submit %> 
	</p>





<% end %>

app/views/brews/_hops.html.erb
<p>
		<%=  f.label :name, "Hops" %>
		<%=  f.text_field :name %>
	

</p>

app/views/brews/_yeasts.html.erb
<p>
		<%=  f.label :name, "Yeast" %>
		<%=  f.text_field :name %>


</p>

app/views/brews/edit.html.erb
<%= render 'form' %>
<%= link_to 'Home', root_path %>

app/views/brews/index.html.erb
<%= link_to "Add a Brew", new_brew_path%> 
	<% @brews.each do |brew| %>
		<h1><%= brew.name %></h1>
	  	<p><%= brew.story %></p>
	   	<p><%= brew.walkthrough %></p>
	   
					<% brew.fermentables.each do |fermentable| %>
					  	<p><%=fermentable.name %></p>
					<% end %>

					<% brew.hops.each do |hop| %>
					  	<p><%=hop.name %></p>
					<% end %>

					<% brew.yeasts.each do |yeasts| %>
					  	<p><%=yeasts.name %></p>
					<% end %>
			

					<% brew.extras.each do |extras| %>
					  	<p><%=extras.name %></p>
					<% end %>
					
				<%= link_to "Show", brew %>
<% end %>

app/views/brews/new.html.erb
<%= render 'form' %>

app/views/brews/show.html.erb
<h1><%= @brew.name %></h1>
  	<p><%= @brew.story %></p>
   	<p><%= @brew.walkthrough %></p>
<fieldset>		
<% @brew.fermentables.each do |fermentable| %>
  	<p><%=fermentable.name.capitalize %> |
<% end %>

<% @brew.hops.each do |hop| %>
  	<%=hop.name.capitalize %> |
<% end %>

<% @brew.yeasts.each do |yeasts| %>
  	<%=yeasts.name.capitalize %> |
<% end %>

<% @brew.extras.each do |extras| %>
  	<%=extras.name.capitalize %></p>
<% end %>
</fieldset>
<%= link_to "Edit", edit_brew_path %>
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrewApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
				

				<p class="notice"><%= notice %></p>
       	<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
<p>You are currently logged in as <%= current_user.email %>. | <%= link_to "Go to brews", brews_path %> | <%= link_to "logout", destroy_user_session_path, method: :destroy %></p>
<% else %>
<%= link_to "Sign Up!", new_user_registration_path %> | <%= link_to "Sign In!", new_user_session_path %>
<% end %>
 
<%= yield %>

</body>
</html>